### ISSUE TITLE
VPN Client

### ISSUE THREAD

**Issue by boshkash1151** [lstein/Net-ISP-Balance#11]
Hi,
Is it possible to install a openvpn client on the router so that all traffic going-out-of/coming-to the LAN be sent through that client tunnel. If possible how could it be configured

Thanks

**Comment by lstein** [comment]
I've updated the library to support openvpn tunneling. Please use version 1.20. The GitHub documentation pages describe how to configure and run this in such a way that you get balancing and failover.
