### ISSUE TITLE
Is there configuration for a failover-only ISP?

### ISSUE THREAD

**Issue by oblitum** [lstein/Net-ISP-Balance#13]
I have a situation where it would be nice to have load balancing, but for one of the ISPs I'd like to just have failover for it in case all others are down, because it's charged differently and it's expensive.

Can I do that with Net-ISP-Balance?

Also, thanks for the project!

**Comment by oblitum** [comment]
Also, thanks for the project.

**Comment by lstein** [comment]
Sorry for the delay in responding. I am an academic researcher and February is grant-writing time.

What you are suggesting is eminently reasonable. I will enter it as a feature request and implement it in the next version. You can **almost** get what you want right now by simply entering a very high value for the weight of the desired ISP. Give the main ISP a weight of 10000 (or higher) and the backup ISP a weight of 1. The backup ISP will now only be used 0.01% of the time.

**Comment by oblitum** [comment]
Thanks!
