### ISSUE TITLE
Feature request: Failover-only ISPs

### ISSUE THREAD

**Issue by lstein** [lstein/Net-ISP-Balance#14]
Designate one or more ISPs as failover-only. They are not used for load balancing.

**Comment by oblitum** [comment]
I'd like to comment that this can take a more general setting, meaning, imagine a situation where balancing is not really of interest, but solely failover ISP, they all could still have their priorities failovering only when higher priority ISP is irresponsive. I see, yeah, this deviates a bit of the original "balancing" intent, but still, seems useful and more general version of the original request.

**Comment by oblitum** [comment]
I'd like to comment that this can take a more general setting, meaning, imagine a situation where balancing is not really of interest, but solely failovering ISPs, they all could still have their priorities, failovering only when higher priority ISP is ping-irresponsive. I see, yeah, this deviates a bit of the original "balancing" intent, but still, seems useful and more general version of the original request.

**Comment by lstein** [comment]
Failover mode is now implemented in version 1.22, released today. You activate it by adding the option "mode=failover" to the configuration file. When running in this mode, the ISP interface with the highest designated weight will be chosen as the default interface. If this ISP becomes unresponsive, then the interface with the next highest weight is chosen, and so forth.
