### ISSUE TITLE
Problem with some websites

### ISSUE THREAD

**Issue by keikurono** [lstein/Net-ISP-Balance#15]
Hi, has anyone tried this website: http://www.bing.com/translator/?

When you use that website, you might have a error message in red: 

> We are experiencing some service problems. Refresh page or try again later

Other site that I have problems is: http://www.dailymotion.com/video/x24gmtq_l-arc-en-ciel-vivid-colors_music
The video loses the connection or it don't have the reply of the video getting the 403 error.

Have you the same problems with those sites?.

**Comment by lstein** [comment]
This has no relationship to net-isp-balance.
