### ISSUE TITLE
How uninstall this?

### ISSUE THREAD

**Issue by sjtosco** [lstein/Net-ISP-Balance#16]
Hi guys!
I installed this soft in my debian distro but i don't know how uninstall this...
Please, help me because i use my PC for work.
Thanks in advance!
Regards

**Comment by lstein** [comment]
Simply remove references to load_balance.pl from your system startup scripts. See http://lstein.github.io/Net-ISP-Balance/ section (7), which describes how to get load_balancing to start at system startup time. Then undo anything you did.

**Comment by sjtosco** [comment]
Thanks!
