### ISSUE TITLE
How to rapidly route internet back to ISP1 when its back online?

### ISSUE THREAD

**Issue by ema07cqc** [lstein/Net-ISP-Balance#33]
Helo there! Thanks for this amazing tool.
I have Cable Internet (ISP1) and 3G modem (ISP2) routed through a Raspberry Pi3b with this setup.

When Cable Internet (ISP1) goes down, 3G modem (ISP2) gets active and it works well.
But when Cable Internet (ISP1) is back online, the active connection keeps using 3G modem (ISP2).

There is a setting to rapidly route internet back to ISP1 when its back online?

Thanks!

**Comment by lstein** [comment]
This should be fixed in version 1.31, just released.
