### ISSUE TITLE
problem in executing script file  Build.PL

### ISSUE THREAD

**Issue by pragnesh036** [lstein/Net-ISP-Balance#34]
I am using raspberry pi 3B+ with Linux os
I will try to implement using the following website  "http://lstein.github.io/Net-ISP-Balance/"
I use ppp0 device as Uc20G GSM module 
I will follow the steps according to sites but in "perl ./Build.PL" it will generate error like 

"root@raspberrypi:/home/pi/Net-ISP-Balance-master# perl ./Build.PL
Can't locate Module/Build.pm in @INC (you may need to install the Module::Build module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at ./Build.PL line 5.
BEGIN failed--compilation aborted at ./Build.PL line 5." 

I do not understand what is the problem 
any suggests ??

**Comment by RichardVieiraS** [comment]
Try run the following command before step 2 (Check and install prerequisites).

`cpan Module::Build
apt-get install libmodule-build-perl libnet-netmask-perl -y`

**Comment by pragnesh036** [comment]
thank you for the replay it's working for me
