### ISSUE TITLE
no gateway when ISP return after fails

### ISSUE THREAD

**Issue by ngiteam** [lstein/Net-ISP-Balance#5]
Hi, Great work!

In my configuration, I have two isp and one lan.
When second ISP fails then is back default getaway disappears in routing table

**##syslog**
```
Sep  7 17:01:34 worldway load_balance.pl[3543]: WAN2 (eth2) is now in state 'down'.
Sep  7 17:01:34 worldway load_balance.pl[3543]: ISP services currently marked up: WAN1

Sep  7 17:31:11 worldway load_balance.pl[3845]: WAN2 (eth2) is now in state 'long_down_to_up'.
Sep  7 17:31:11 worldway load_balance.pl[3845]: ISP services currently marked up: WAN1 WAN2
Sep  7 17:31:11 worldway load_balance.pl[3846]: WAN2 (eth2) is now in state 'up'.
Sep  7 17:31:11 worldway load_balance.pl[3846]: ISP services currently marked up: WAN1 WAN2
```

**Comment by djeraseit** [comment]
Same issue. On return of ISP #2 entire box becomes unresponsive to ping

**Comment by lstein** [comment]
I apologize for not noting this issue. I will try to reproduce.  Oddly I use the package extensively on my unreliable home network where one ISP or another goes down several times per week and have not encountered this. Are you using the current master branch?

**Comment by djeraseit** [comment]
Hello Mr. Stein,

Thank you for your quick reply.

The file I downloaded is
lstein-Net-ISP-Balance-release-1_14-3-g00e5300.tar.gz
When untarred it is lstein-Net-ISP-Balance-00e5300.

What do you think about my response to the lsm not starting issue. Would my
cited change make it work? I am unable to test until tomorrow.

**Comment by lstein** [comment]
There seems to be a problem with the lsm package not being able to monitor an interface that loses its IP address and then regains it later. I am doing further debugging and hope to have a solution shortly.

**Comment by lstein** [comment]
To all following this bug report: please checkout the git branch named "lsm-debugging". It fixes the problem of the gateway not coming back when an interface goes completely down and then comes back later (as opposed to suffering packet loss). Let me know if it improves the problem. There is still a problem when the interface goes down and comes back with a different dynamic IP address. I am working on it.

**Comment by lstein** [comment]
Version 1.18 should fix this issue. Now released on CPAN.
