### ISSUE TITLE
IP Forwarding On Arch Linux

### ISSUE THREAD

**Issue by djeraseit** [lstein/Net-ISP-Balance#7]
FYI: To get IP Forwarding to work on Arch Linux see:

https://wiki.archlinux.org/index.php/Internet_sharing#Enable_packet_forwarding

Specifically you need to add the following: 

IPForward=kernel

**Comment by lstein** [comment]
Thanks for the hint. I'll add it to the instructions.

**Comment by lstein** [comment]
I've added this instruction to the github.io pages.
